/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgerRouteImport } from './routes/_ledger'
import { Route as LedgerIndexRouteImport } from './routes/_ledger/index'

const LedgerRoute = LedgerRouteImport.update({
  id: '/_ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ledger': typeof LedgerRouteWithChildren
  '/_ledger/': typeof LedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_ledger' | '/_ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LedgerRoute: typeof LedgerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ledger': {
      id: '/_ledger'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ledger/': {
      id: '/_ledger/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof LedgerRoute
    }
  }
}

interface LedgerRouteChildren {
  LedgerIndexRoute: typeof LedgerIndexRoute
}

const LedgerRouteChildren: LedgerRouteChildren = {
  LedgerIndexRoute: LedgerIndexRoute,
}

const LedgerRouteWithChildren =
  LedgerRoute._addFileChildren(LedgerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LedgerRoute: LedgerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
