// This client was generated by Platformatic from an OpenAPI specification.

import type { GeneratedClient } from './generated-client-types'
import type * as Types from './generated-client-types'

// The base URL for the API. This can be overridden by calling `setBaseUrl`.
let baseUrl = ''
// The default headers to send within each request. This can be overridden by calling `setDefaultHeaders`.
let defaultHeaders = {}
// The additional parameters you want to pass to the `fetch` instance.
let defaultFetchParams = {}
const defaultJsonType = { 'Content-type': 'application/json; charset=utf-8' }

function sanitizeUrl(url: string) : string {
  if (url.endsWith('/')) { return url.slice(0, -1) } else { return url }
}
export const setBaseUrl = (newUrl: string) : void => { baseUrl = sanitizeUrl(newUrl) }

export const setDefaultHeaders = (headers: object): void => { defaultHeaders = headers }

export const setDefaultFetchParams = (fetchParams: RequestInit): void => { defaultFetchParams = fetchParams }

type JSON = Record<string, unknown>
/* @ts-ignore - potential unused variable */
function headersToJSON(headers: Headers): JSON {
  const output: JSON = {}
  headers.forEach((value, key) => {
    output[key] = value
  })
  return output
}

const _healthCheck = async (url: string, request: Types.HealthCheckRequest): Promise<Types.HealthCheckResponses> => {
  const headers: HeadersInit = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/health`, {
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status as 200,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status as 200,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

export const healthCheck: GeneratedClient['healthCheck'] = async (request: Types.HealthCheckRequest): Promise<Types.HealthCheckResponses> => {
  return await _healthCheck(baseUrl, request)
}
const _listTransactions = async (url: string, request: Types.ListTransactionsRequest): Promise<Types.ListTransactionsResponses> => {
  const headers: HeadersInit = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/transactions`, {
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status as 200,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status as 200,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

export const listTransactions: GeneratedClient['listTransactions'] = async (request: Types.ListTransactionsRequest): Promise<Types.ListTransactionsResponses> => {
  return await _listTransactions(baseUrl, request)
}
const _createTransaction = async (url: string, request: Types.CreateTransactionRequest): Promise<Types.CreateTransactionResponses> => {
  const body = 'body' in request ? (request.body) : undefined
  const isFormData = body instanceof FormData
  const headers: HeadersInit = {
    ...defaultHeaders,
    ...(isFormData || body === undefined) ? {} : defaultJsonType
  }

  const response = await fetch(`${url}/transactions`, {
    method: 'POST',
    body: isFormData ? body : JSON.stringify(body),
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [201, 400]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status as 201 | 400,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status as 201 | 400,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

export const createTransaction: GeneratedClient['createTransaction'] = async (request: Types.CreateTransactionRequest): Promise<Types.CreateTransactionResponses> => {
  return await _createTransaction(baseUrl, request)
}
const _getTransaction = async (url: string, request: Types.GetTransactionRequest): Promise<Types.GetTransactionResponses> => {
  const headers: HeadersInit = {
    ...defaultHeaders
  }

  const response = await fetch(`${url}/transactions/${request.path['id']}`, {
    headers,
    ...defaultFetchParams
  })

  const jsonResponses = [200, 404]
  if (jsonResponses.includes(response.status)) {
    return {
      statusCode: response.status as 200 | 404,
      headers: headersToJSON(response.headers),
      body: await response.json()
    }
  }
  const responseType = response.headers.get('content-type')?.startsWith('application/json') ? 'json' : 'text'
  return {
    statusCode: response.status as 200 | 404,
    headers: headersToJSON(response.headers),
    body: await response[responseType]()
  }
}

export const getTransaction: GeneratedClient['getTransaction'] = async (request: Types.GetTransactionRequest): Promise<Types.GetTransactionResponses> => {
  return await _getTransaction(baseUrl, request)
}
type BuildOptions = {
  headers?: object
}
export default function build (url: string, options?: BuildOptions) {
  url = sanitizeUrl(url)
  if (options?.headers) {
    defaultHeaders = options.headers
  }
  return {
    healthCheck: _healthCheck.bind(url, ...arguments),
    listTransactions: _listTransactions.bind(url, ...arguments),
    createTransaction: _createTransaction.bind(url, ...arguments),
    getTransaction: _getTransaction.bind(url, ...arguments)
  }
}